"$schema" = 'https://starship.rs/config-schema.json'
 
format = """
$os\
$username\
[](bg:mantle fg:surface0)\
$directory\
\
$git_branch\
$git_status\
\
$dotnet\
$rust\
$golang\
$nodejs\
$python\
$fill\
\
$line_break\
$character"""
 
palette = 'catppuccin_mocha'
 
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
 
[os]
disabled = false
style = "bg:surface0 fg:text"
format = "[ $symbol]($style)"
 
[os.symbols]
Linux = ""
Macos = ""
Windows = ""
Ubuntu = ""
NixOS = ''

[fill]
symbol = ' '
 
[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'
 
[directory]
style = "fg:mantle bg:peach"
format = "[](bg:peach fg:mantle)[ $path ]($style)[](bg:mantle fg:peach)"
truncation_length = 3
truncation_symbol = "../"
 
[git_branch]
symbol = ""
style = "bg:teal"
format = "[](bg:green fg:mantle)[[ $symbol $branch ](fg:base bg:green)]($style)"
 
[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)[](bg:mantle fg:green)'
 
[nodejs]
symbol = ""
style = "bg:teal"
format = '[](bg:teal fg:mantle)[[ $symbol( $version) ](fg:base bg:teal)]($style)[](bg:mantle fg:teal)'
 
[dotnet]
format = '[](bg:teal fg:mantle)[ $symbol$tfm ](fg:base bg:teal)[](bg:mantle fg:teal)'
symbol = ' .NET '
 
[rust]
symbol = ""
style = "bg:teal"
format = '[](bg:teal fg:mantle)[[ $symbol( $version) ](fg:base bg:teal)]($style)[](bg:mantle fg:teal)'
 
[golang]
symbol = ""
style = "bg:teal"
format = '[](bg:teal fg:mantle)[[ $symbol( $version) ](fg:base bg:teal)]($style)[](bg:mantle fg:teal)'
 
[python]
symbol = ""
style = "bg:teal"
format = '[](bg:teal fg:mantle)[[ $symbol( $version) ](fg:base bg:teal)]($style)[](bg:mantle fg:teal)'
 
[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'
 
[line_break]
disabled = false
 
[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
