set number
set relativenumber

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set autoindent
set smartindent

set nowrap

set noswapfile
set nobackup
set undodir=$HOME/.vim/undodir
set undofile

set nohlsearch
set smartcase
set ignorecase
set incsearch

set termguicolors

set scrolloff=8
set signcolumn=yes
set isfname+=@-@

set updatetime=50

set exrc

if has('nvim')
    set inccommand=split
endif

if has('nvim-0.10')
    set winborder=rounded
endif

let mapleader=" "

" Move selected lines up and down
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Keep cursor in place when joining lines
nnoremap J mzJ`z

" Keep cursor in the middle when jumping or searching
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv

" Keep yanked word when pasting over text
xnoremap <leader>p "_dP

" Delete without overriding yanked value
nnoremap <leader>d "_d
vnoremap <leader>d "_d

" Yank to clipboard (asbjornHaland)
nnoremap <leader>y "+y
vnoremap <leader>y "+y
nnoremap <leader>Y "+Y

" Other
nnoremap Q <nop>
