# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = [workspace 1 silent] zen-browser
exec-once = hyprctl keyword windowrule "match:class spotify, workspace 9 silent" \
            && spotify \
            && sleep 5 \
            && hyprctl keyword windowrule "match:class spotify, workspace unset" \
            && hyprctl dispatch workspace 1

exec-once = vicinae server
