eval "$(starship init bash)"
eval "$(zoxide init bash)"

# avoid exiting on ctrl+D
set -o ignoreeof

# set aliases only if aliased commands exist
if command -v z 2>&1 >/dev/null; then 
    alias cd="z"
    alias zz="z -"
fi

if command -v eza 2>&1 >/dev/null; then 
    alias ls="eza"
    alias tree="eza --tree"
fi

if command -v bat 2>&1 >/dev/null; then 
    alias cat="bat --paging=never"
fi

if command -v fzf 2>&1 >/dev/null; then 
    alias fzf="fzf --height 40% --preview 'bat --color=always --style=numbers --line-range=:500 {}' | tee >(pbcopy)"
fi

if command -v rip 2>&1 >/dev/null; then 
    alias trash="rip"
fi

if command -v lazygit 2>&1 >/dev/null; then 
    alias lg="lazygit"
fi
