# Bash
INSTALLER_CONFIG_SOURCE=$INSTALLER_DIRECTORY/bashrc
INSTALLER_CONFIG_DESTINATION=$HOME/.bashrc

configure

# Zsh
INSTALLER_CONFIG_SOURCE=$INSTALLER_DIRECTORY/zshrc
INSTALLER_CONFIG_DESTINATION=$HOME/.zshrc

configure
