# avoid exiting on ctrl+D
set -o ignoreeof

if command -v bat 2>&1 >/dev/null; then 
    alias cat="bat --paging=never"
fi

if command -v lazygit 2>&1 >/dev/null; then 
    alias lg="lazygit"
fi

if command -v claude 2>&1 >/dev/null; then 
    alias claude="claude -c"

    # "command" tells it to use the original command, not the aliased one
    alias claude-new="command claude" 
fi

if command -v nvim 2>&1 >/dev/null; then
    alias vim="nvim"
    alias vi="nvim"
fi

if command -v zoxide 2>&1 >/dev/null; then
    if [ -n "$ZSH_VERSION" ]; then
        eval "$(zoxide init zsh)"
    else
        eval "$(zoxide init bash)"
    fi

    if command -v z 2>&1 >/dev/null; then
        alias cd="z"
        alias zz="z -"
    fi
fi

if command -v rip 2>&1 >/dev/null; then
    alias trash="rip"
fi

if command -v starship 2>&1 >/dev/null; then
    if [ -n "$ZSH_VERSION" ]; then
        eval "$(starship init zsh)"
    else
        eval "$(starship init bash)"
    fi
fi
